# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdate',
            name='mdateid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=b'ID'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voteid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=b'ID'),
        ),
    ]
